OPENAI_API_KEY="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"
ANYSCALE_API_KEY="esecret_abymxdjqflad5ijb3vkdb3f1fw"
ANYSCALE_BASE_URL="https://api.endpoints.anyscale.com/v1"
MONGO_AUTH='mongodb+srv://admin:rGNne8mH7odYlAEx@cluster0.cboqxkk.mongodb.net/'
STRIPE_API_KEY='sk_test_51OwpyqP9cw7YNYKfIEs6jzwZoNwZhPnptntoKlrd9rQI5SJ2Kro1U4AyEmLBlrfKLgDhLxaLfWdq7lxokfWkh34200bHPP2IgS'
STRIPE_PAYMENT_URL='https://buy.stripe.com/test_aEUaHb78Wfe46Yg4gg '
YOUR_EMAIL=''
YOUR_EMAIL_PASS=''
VERIFICATION_URL=''